#+TITLE: Yonei's Emacs config
#+AUTHOR: Yonei <yonei@proton.me>
#+STARTUP: showeverything
#+OPTIONS: toc:2

* Table of contents :toc:
- [[#important-stuff-to-load-first][Important stuff to load first]]
  - [[#add-the-scripts-directory-to-path][Add the scripts directory to path]]
  - [[#source-the-scripts][Source the scripts]]
  - [[#evil-mode][Evil mode]]
  - [[#keybinds][Keybinds]]
- [[#visual-tweaks][Visual tweaks]]
  - [[#theme][Theme]]
  - [[#fonts][Fonts]]
  - [[#beacon][Beacon]]
  - [[#icons][Icons]]
  - [[#modeline][Modeline]]
- [[#sane-defaults][Sane defaults]]
- [[#dashboard][Dashboard]]
- [[#dired][Dired]]
  - [[#dired-collapse][Dired collapse]]
  - [[#human-readable-sizes][Human readable sizes]]
- [[#org-mode][Org mode]]
  - [[#mode-specific-keybindings][Mode specific keybindings]]
  - [[#table-of-contents][Table of contents]]
  - [[#org-bullets][Org bullets]]
  - [[#org-tempo][Org tempo]]
  - [[#wysiwyg][WYSIWYG]]
  - [[#visual-tweaks-1][Visual tweaks]]

* Important stuff to load first
** Add the scripts directory to path
#+begin_src elisp
(add-to-list 'load-path (expand-file-name "scripts" user-emacs-directory))
#+end_src

** Source the scripts
#+begin_src elisp
(require 'elpaca-bootstrap)  ;; Elpaca package manager setup
(require 'buffer-move)       ;; Move splits with ease
#+end_src

** Evil mode
#+begin_src elisp
;; Enable Evil
(use-package evil
  :elpaca t
  :init
  (setq evil-want-keybinding nil)
  (evil-mode))

;; Evil mode functionality for various other tools
(use-package evil-collection
  :elpaca t
  :after evil
  :config
  (setq evil-collection-mode-list '(dashboard dired help ibuffer))
  (evil-collection-init))
#+end_src

** Keybinds
#+begin_src elisp
(use-package general
  :elpaca t
  :config
  (general-evil-setup)

  ;; Set 'SPC' as global leader key
  (general-create-definer yonei/leader-keys
    :states '(normal insert visual emacs)
    :keymaps 'override
    :prefix "SPC" ;; leader key
    :global-prefix "M-SPC") ;; leader key for insert mode

  (yonei/leader-keys
    "." '(find-file :wk "File search")
    "," '(switch-to-buffer :wk "Switch to buffer")

    "b" '(:ignore t :wk "buffer")
    "b i" '(ibuffer :wk "iBuffer")
    "b k" '(kill-this-buffer :wk "Kill current buffer")
    "b n" '(next-buffer :wk "Next buffer")
    "b p" '(previous-buffer :wk "Previous buffer")
    "b r" '(revert-buffer :wk "Reload buffer")

    "w" '(:ignore t :wk "window")
    "w c" '(delete-window :wk "Close current window")
    "w n" '(evil-window-vnew :wk "New window")
    "w s" '(evil-window-split :wk "Horizontal split")
    "w v" '(evil-window-vsplit :wk "Vertical split")
    ;; Window navigation
    "w h" '(evil-window-left :wk "Window left")
    "w j" '(evil-window-down :wk "Window down")
    "w k" '(evil-window-up :wk "Window up")
    "w l" '(evil-window-right :wk "Window right")
    "w w" '(evil-window-next :wk "Goto next window")
    ;; Window movement
    "w H" '(buf-move-left :wk "Buffer move left")
    "w J" '(buf-move-down :wk "Buffer move down")
    "w K" '(buf-move-up :wk "Buffer move up")
    "w L" '(buf-move-right :wk "Buffer move right")

    "e v" '(:ignore t :wk "evaluate")
    "e v b" '(eval-buffer :wk "Evaluate elisp in buffer")
    "e v d" '(eval-defun :wk "Evaluate defun containing or after point")
    "e v e" '(eval-expression :wk "Evaluate and elisp expression")
    "e v l" '(eval-last-sexp :wk "Evaluate elisp expression before point")
    "e v r" '(eval-region :wk "Evaluate elisp in region")

    "f" '(:ignore t :wk "file")
    "f r" '(recentf :wk "Find recent files")
    "f c" '((lambda () (interactive)
              (find-file (expand-file-name "config.org" user-emacs-directory)))
            :wk "Open emacs config.org")

    "h" '(:ignore t :wk "help")
    "h f" '(describe-function :wk "Describe function")
    "h v" '(describe-variable :wk "Describe variable")
    "h r r" '((lambda () (interactive)
                (load-file user-init-file)
                (ignore (elpaca-process-queues)))
              :wk "Reload emacs config")))

;; Exit the minibuffer by pressing 'ESC' 1 time instead of 3
(global-set-key (kbd "<escape>") 'keyboard-escape-quit)
#+end_src

*** Which-key
#+begin_src elisp
(use-package which-key
  :elpaca t
  :init
  (which-key-mode 1)
  :config
  (setq which-key-popup-type 'minibuffer
        which-key-sort-order #'which-key-key-order-alpha
        which-key-sort-uppercase-first nil
        which-key-add-column-padding 1
        which-key-max-display-columns nil
        which-key-min-display-lines 6
        which-key-side-window-slot -10
        which-key-side-window-max-height 0.25
        which-key-idle-delay 0.8
        which-key-max-description-length 25
        which-key-allow-imprecise-window-fit t
        which-key-separator " → " ))
#+end_src


* Visual tweaks
** Theme
#+begin_src elisp
(use-package doom-themes
  :elpaca t
  :config
  ;; Global settings (defaults)
  ;; Set either to nil to universally disable
  (setq doom-themes-enable-bold t
        doom-themes-enable-italic t)
  (load-theme 'doom-one t)

  ;; Enable flashing mode-line on errors
  (doom-themes-visual-bell-config)
  ;; Corrects (and improves) org-mode's native fontification.
  (doom-themes-org-config))
#+end_src

** Fonts
TODO: Adjust this later
#+begin_src elisp
(set-face-attribute 'default nil
  :font "JetBrainsMono Nerd Font"
  :height 120
  :weight 'medium)
(set-face-attribute 'variable-pitch nil
  :font "Overpass"
  :height 140
  :weight 'medium)
(set-face-attribute 'fixed-pitch nil
  :font "JetBrainsMono Nerd Font"
  :height 120
  :weight 'medium)

;; Make commented text and keywords italics.
(set-face-attribute 'font-lock-comment-face nil :slant 'italic)
(set-face-attribute 'font-lock-keyword-face nil :slant 'italic)

;; This sets the default font on all graphical frames created after restarting Emacs.
;; Does the same thing as 'set-face-attribute default' above, but emacsclient fonts
;; are not right unless I also add this method of setting the default font.
(add-to-list 'default-frame-alist '(font . "JetBrains Mono-12"))
#+end_src

** Beacon
Silly, visually pleasing cursor effect that helps you locate the cursor.
#+begin_src elisp
(use-package beacon
  :elpaca t
  :init
  (beacon-mode 1))
#+end_src

** Icons
#+begin_src elisp
(use-package all-the-icons
  :elpaca t
  :if (display-graphic-p))

(use-package nerd-icons
  :elpaca t)
#+end_src

** Modeline
#+begin_src elisp
(use-package doom-modeline
  :ensure t
  :init (doom-modeline-mode 1)
  :config
  (setq doom-modeline-buffer-file-name-style 'truncate-nil)
  (setq doom-modeline-total-line-number t)
  (display-battery-mode 1)
  (column-number-mode 1))
#+end_src


* Sane defaults
#+begin_src elisp
(delete-selection-mode 1)             ;; Delete selected text by typing
(menu-bar-mode -1)                    ;; Disable menu bar
(tool-bar-mode -1)                    ;; Disable tool bar
(scroll-bar-mode -1)                  ;; Disable scroll bar
(global-display-line-numbers-mode 1)  ;; Display line numbers
(global-visual-line-mode t)           ;; Wrap lines by default
(global-auto-revert-mode t)           ;; Automatically show changes if the file has changed

(setq org-edit-src-content-indentation 0  ;; Org src block automatic indent from 2 to 0
      delete-by-moving-to-trash t)        ;; Move files to trash when deleting
(defalias 'yes-or-no-p 'y-or-n-p)         ;; Answer just 'y' or 'n' instead of full words
#+end_src


* Dashboard
#+begin_src elisp
(use-package dashboard
  :elpaca t
  :config
  (add-hook 'elpaca-after-init-hook #'dashboard-insert-startupify-lists)
  (add-hook 'elpaca-after-init-hook #'dashboard-initialize)
  (dashboard-setup-startup-hook)

  ;; Show dashboard in frames created by 'emacsclient -c'.
  (setq initial-buffer-choice (lambda () (get-buffer-create "*dashboard*")))
  (setq dashboard-startup-banner 'logo
        dashboard-center-content t
        dashboard-icon-type 'all-the-icons
        dashboard-set-file-icons t))
#+end_src

* Dired
** Dired collapse
Mimic how GitHub renders file paths: if there is a chain of directories where each one only has one child, they are concatenated together and shown on the first level in this collapsed form.
#+begin_src elisp
(use-package dired-collapse
  :elpaca t
  :hook (dired-mode . dired-collapse-mode))
#+end_src

** Human readable sizes
#+begin_src elisp
(setq dired-listing-switches "-alh")
#+end_src


* Org mode
** Mode specific keybindings
#+begin_src elisp
(add-hook 'org-mode-hook (lambda ()
  (local-set-key (kbd "<tab>") 'org-cycle))  ;; Fold headings
)
#+end_src

** Table of contents
#+begin_src elisp
(use-package toc-org
  :elpaca t
  :commands toc-org-enable
  :hook (org-mode . toc-org-enable))
#+end_src

** Org bullets
#+begin_src elisp
(add-hook 'org-mode-hook 'org-indent-mode)
(use-package org-bullets
  :elpaca t
  :hook (org-mode . org-bullets-mode))
#+end_src

** Org tempo
The =org-tempo= module allows inserting structural blocks with a few keystrokes.
Org Tempo expands snippets to structures defined in =org-structure-template-alist= and =org-tempo-keywords-alist=.

| Typing the below + TAB | Expands to ...                          |
|------------------------+-----------------------------------------|
| <a                     | '#+BEGIN_EXPORT ascii' … '#+END_EXPORT  |
| <c                     | '#+BEGIN_CENTER' … '#+END_CENTER'       |
| <C                     | '#+BEGIN_COMMENT' … '#+END_COMMENT'     |
| <e                     | '#+BEGIN_EXAMPLE' … '#+END_EXAMPLE'     |
| <E                     | '#+BEGIN_EXPORT' … '#+END_EXPORT'       |
| <h                     | '#+BEGIN_EXPORT html' … '#+END_EXPORT'  |
| <l                     | '#+BEGIN_EXPORT latex' … '#+END_EXPORT' |
| <q                     | '#+BEGIN_QUOTE' … '#+END_QUOTE'         |
| <s                     | '#+BEGIN_SRC' … '#+END_SRC'             |
| <v                     | '#+BEGIN_VERSE' … '#+END_VERSE'         |

#+begin_src elisp
(require 'org-tempo)
#+end_src

** WYSIWYG
Disable WYSIWYG while mousing over in insert mode for easier editing.
#+begin_src elisp
(use-package org-appear
  :elpaca t
  :hook (org-mode . org-appear-mode)
  :config
  (setq org-hide-emphasis-markers t
        org-appear-autolinks t
        org-appear-trigger 'manual)

  ;; Additional hook for Evil mode integration
  :hook (org-mode . (lambda ()
                      (add-hook 'evil-insert-state-entry-hook
                                #'org-appear-manual-start
                                nil
                                t)
                      (add-hook 'evil-insert-state-exit-hook
                                #'org-appear-manual-stop
                                nil
                                t))))
#+end_src

** Visual tweaks
*** Different list characters per embedding level
[[https://emacs.stackexchange.com/a/45727]]

#+begin_src elisp
;; First
(font-lock-add-keywords 'org-mode
  '(("^\\(-\\) "
    (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "•"))))))
;; Second embedding
(font-lock-add-keywords 'org-mode
  `((,(concat "^[[:space:]]\\{" (number-to-string
                                (+ 2 org-list-indent-offset)) "\\}\\(-\\) ")
    (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "◦"))))))
;; Third embedding
(font-lock-add-keywords 'org-mode
  `((,(concat "^[[:space:]]\\{" (number-to-string
                                (* 2 (+ 2 org-list-indent-offset))) "\\}\\(-\\) ")
    (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "▸"))))))
;; Forth embedding
(font-lock-add-keywords 'org-mode
  `((,(concat "^[[:space:]]\\{" (number-to-string
                                (* 3 (+ 2 org-list-indent-offset))) "\\}\\(-\\) ")
    (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "▹"))))))
#+end_src

*** Nice folding characters
#+begin_src elisp
(setq org-ellipsis " ▼ ")
#+end_src

*** Center Org buffers for readability
#+begin_src elisp
(use-package visual-fill-column
  :elpaca t
  :hook (org-mode . visual-fill-column-mode)
  :config
  (setq-default visual-fill-column-width 100
                visual-fill-column-center-text t))
#+end_src

*** Heading sizes
#+begin_src elisp
(custom-set-faces
  '(org-level-1 ((t (:inherit outline-1 :height 1.5))))
  '(org-level-2 ((t (:inherit outline-2 :height 1.3))))
  '(org-level-3 ((t (:inherit outline-3 :height 1.15))))
  '(org-level-4 ((t (:inherit outline-4 :height 1.05))))
  '(org-document-title ((t (:height 1.75 :underline nil)))))
#+end_src
